/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Collection: typeof import('./src/components/firebase/firestore/Collection.vue')['default']
    Document: typeof import('./src/components/firebase/firestore/Document.vue')['default']
    FirebaseApp: typeof import('./src/components/firebase/FirebaseApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/firebase/auth/User.vue')['default']
  }
}
